exports.sports = [
  "Basketball",
  "Biking",
  "Bouldering",
  "Bowling",
  "Fishing",
  "Football",
  "Golf",
  "Hiking",
  "Hockey",
  "Hunting",
  "Martial Arts",
  "Running",
  "Skiing",
  "Showboardig",
  "Soccer",
  "Surfing",
  "Swimming",
  "Tennis",
  "Volleyball",
  "Weight Training",
  "Yoga",
];
exports.activities = [
  "Blogging",
  "Board Games",
  "Engineering",
  "Music",
  "Painting/Drawing",
  "Photography",
  "Reading",
  "Writing",
  "Woodwork",
];
exports.travel = ["Backpacking", "Camping", "Cruises", "Mountains", "Ocean"];
exports.music = [
  "Blues",
  "CCM",
  "Classical",
  "Country",
  "EDM",
  "Electronica",
  "Indie/Alternative",
  "Jazz",
  "Metal",
  "Pop",
  "R&B",
  "Rap",
  "Rock",
  "Worship",
];
exports.food = [
  "Baking",
  "Coffee",
  "Cooking",
  "Healthy Eating",
  "Vegan",
  "Vegitarian",
];
