// User reducer types
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_USER = "SET_USER";
export const MARK_MESSAGES_READ = "MARK_MESSAGES_READ";
export const MARK_NOTIFICATIONS_READ = "MARK_NOTIFICATIONS_READ";
// UI reducer types
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const LOADING_UI = "LOADING_UI";
export const LOADING_SECONDARY_UI = "LOADING_SECONDARY_UI";
export const SET_ERRORS = "SET_ERRORS";
export const STOP_LOADING_UI = "STOP_LOADING_UI";
// Data reducer types
export const CLEAR_DATA = "CLEAR_DATA";
export const LIKE_USER = "LIKE_USER";
export const PASS_USER = "PASS_USER";
export const SET_CONVERSATION = "SET_CONVERSATION";
export const SET_CONVERSATIONS = "SET_CONVERSATIONS";
export const SET_EXPLORE = "SET_EXPLORE";
export const SET_FORGOT_PASSWORD_SENT = "SET_FORGOT_PASSWORD_SENT";
export const SET_MATCHES = "SET_MATCHES";
export const SET_MESSAGE = "SET_MESSAGE";
export const SET_NOTIFICATIONS = "SET_NOTIFICATIONS";
export const SET_PROFILE = "SET_PROFILE";
export const SET_REPORT_USER = "SET_REPORT_USER";
export const SET_SETTINGS_EDITED = "SET_SETTINGS_EDITED";
export const SET_SETTINGS = "SET_SETTINGS";
export const SET_UNMATCH = "SET_UNMATCH";
export const SET_VERIFICATION_RESENT = "SET_VERIFICATION_RESENT";
